server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/users/**
              filters:
                - Auth

            - id: courseservice
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/courses/**
              filters:
                - ConditionalAuth

            - id: authservice
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/auth/**

            - id: reviewservice
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/reviews

            - id: modulesservice
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/modules
              filters:
                - ConditionalAuth

            - id: lessonsservice
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/lessons
              filters:
                - ConditionalAuth

            - id: progressService
              uri: http://localhost:8088
              predicates:
                - Path=/api/v1/
              filters:
                - Auth

            - id: notificationservice
              uri: http://localhost:8089
              predicates:
                - Path=/api/v1/notifications
              filters:
                - Auth

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always

auth:
  tokens:
    secret: ${JWT_SECRET:mysuperlongsecretkey_for_docker_12345678901234567890}

logging:
  level:
    org.springframework.cloud.gateway: INFO
